config/routes.rb
Geoinfotour::Application.routes.draw do
  devise_for :users

  root :to => redirect('/' + I18n::t('url_routing.destinations') + '/')

  sections = ['destinations', 'routes', 'events', 'terms', 'personalities']
  sections.each do |section|
    match("#{section}/" => "#{section}#index",
          :defaults => { :category_name => "#{section}"}, :via => :get)
    match("#{section}/:id" => "#{section}#show",
          :constraints => {:id => /\d+/}, :via => :get)
    match("#{section}/:id/publish" => "#{section}#publish",
          :constraints => {:id => /\d+/}, :via => :post, :as => "publish_#{section.singularize}")
    match("#{section}/:id/unpublish" => "#{section}#unpublish",
          :constraints => {:id => /\d+/}, :via => :post, :as => "unpublish_#{section.singularize}")
    match "#{section}/new" => "#{section}#new", :via => :get
    match "#{section}/drafts" => "#{section}#drafts", :via => :get
    match "#{section}/:category_name" => "#{section}#index", :via => :get
    resources section
  end

  sections.each do |section|
    match(I18n::t("url_routing.#{section}") + '/' => "#{section}#index",
          :defaults => { :category_name => "#{section}"}, :via => :get)
    match("#{I18n::t 'url_routing.' + section}/:id(/:title)" => "#{section}#show",
          :constraints => {:id => /\d+/}, :via => :get)
    match "#{I18n::t 'url_routing.' + section}/:category_name" => "#{section}#index", :via => :get
  end

  match("#{I18n::t("url_routing.maps")}/" => "maps#index", :via => :get)

  resources :users

end

app/views/layouts/application.html.haml
!!!html
%html{:lang => 'cz'}
  %head
    %meta{:charset => 'utf-8'}
    %title Geoinfotour
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    /[if lt IE 9]
      = javascript_include_tag "html5shiv"
  %body
    .navbar
      .navbar-inner
        .container
          = link_to "GeoInfoTour", '/', { :class => 'brand' }
          %p.navbar-text= t(:site_subtitle)
          %img#logo-image{ :src => '/icons/logo.jpg', :height => 100 }
          %ul.nav
            - Category.root.each do |c|
              - active = "active" if current_section == c
              %li{ :class => "#{active}" }
                = link_to t(c.name), "/#{t 'url_routing.' + c.name}/", { :rel => c.name }
            %li= link_to t(:maps), "/#{t 'url_routing.maps'}/"
          - if current_user
            %ul.nav.pull-right
              %li.dropdown
                %a.dropdown-toggle{ "data-toggle" => "dropdown", :href =>"#"}
                  = t(:actions)
                  %b.caret
                %ul.dropdown-menu
                  - if current_section
                    %li= link_to t(:new_document), "/#{current_section.name}/new", { :id => :new_document}
                    - if action_name == 'show'
                      %li= link_to t(:edit_document), "/#{current_section.name}/#{@doc.id}/edit", :rel => 'edit'
                    - if ['show', 'edit'].include? action_name
                      %li= link_to t(:delete_document), "/#{current_section.name}/#{@doc.id}/", :method => :delete, :confirm => t(:deletion_confirmation, :title => @doc.title), :rel => 'delete'
                      %li.hidden= button_to "delete document", "/#{current_section.name}/#{@doc.id}/", :method => :delete, :form => {:name => "delete_document"}
                      - if @doc.draft?
                        %li= link_to t(:publish), polymorphic_path([:publish, @doc]), :method => :post, :rel => 'publish'
                      - else
                        %li= link_to t(:unpublish), polymorphic_path([:unpublish, @doc]), :method => :post, :rel => 'unpublish'
                    %li= link_to t(:list_drafts), "/#{current_section.name}/drafts", { :rel => 'drafts' }
              %li.dropdown
                %a.dropdown-toggle{ "data-toggle" => "dropdown", :href =>"#"}
                  = current_user.name
                  %b.caret
                %ul.dropdown-menu
                  %li= link_to t(:log_out), destroy_user_session_path, :method => :delete, :rel => 'logout'

    - if @breadcrumbs.present?
      %nav#breadcrumbs
        %ul.breadcrumb
          %li= t(:breadcrumbs)
          - @breadcrumbs.each do |b|
            - last = (b == @breadcrumbs.last)
            %li{ :class => "#{'active' if last}" }
              - title = (b.class == Category) ? t(b.name) : b.name
              = link_to title, category_path(b), :class => b.name
            - unless last
              %span.divider /

    .container-fluid
      .row-fluid
        #sidebar.span3
          - if @current_category.present?
            %nav#categories-pane
              %ul.nav.nav-list
                - if params[:id].present?
                  %li.nav-header= t(:back)
                  %li= link_to t(@current_category.name), category_path(@current_category)
                - elsif not @current_category.root?
                  %li.nav-header= t(:back)
                  - parent = @current_category.parent
                  %li= link_to t(parent.name), category_path(parent)

                %li.nav-header= t(:categories)
                - if @current_category.children.present?
                  - @current_category.children.each do |c|
                    %li.child= link_to t(c.name), category_path(c), :class => c.path.map(&:name).join(' '), :rel => c.name
                - else
                  %li= t(:no_categories)
        #content.span9
          - if notice.present?
            %p.alert.alert-info.alert-block= notice
          - if alert.present?
            %p.alert.alert-block= alert
          - if flash[:error].present?
            %p.alert.alert-error.alert-block= flash[:error]

          - if current_section && action_name == 'index'
            %h3= t(:search_documents, :category => t(@current_category.name))
            %form
              %input#search{ :type => 'text', :name => 'q', :value => params[:q] }
              %input#search_button{ :type => 'submit', :value => t(:search) }
            - if @documents.blank?
              %p.not-found= t(:no_documents_found)
          = yield

      %hr
      %footer
        %p= t(:copyright_notice)
        %p!= t(:this_program_is_free_software)
    = javascript_include_tag "application"
    = yield :scripts